### ISSUE TITLE
No output after configuration

### ISSUE THREAD

**Issue by Zakaren** [DFIR-ORC/dfir-orc-config#1]
Hi, 

I successfully compiled the ORC project.
To make a test configuration, I used the two binaries *DFIR-ORC-x86.exe* and *DFIR-ORC-x64.exe* from two folders *build-x86\MinSizeRel* and *build-x64\MinSizeRel* and I put them alongside *autorunsc.exe* on the *tools* folder.

I didn't change anything on the two other folders : *output* and *config*.

After executing the *configure.cmd* file, I got the following message : 
> Configuring Orc (.\output\DFIR-Orc.exe) with config: .\config

And an empty folder named *%ORC_OUTPUT%* is created after that in the *output* folder.

Could you please tell me if I did something wrong ?

**Comment by jgautier-anssi** [comment]
Hi Zakaren,

Thank you for your interest in DFIR-Orc.exe.
We can reproduce the behavior you describe if the configure.cmd is not run from an elevated prompt. Is that what you were doing?

If so, apologies for not documenting better this requirement in the README.
(we'll do so shortly)

We will also in the next few days publish an update and tutorial we hope you will find useful to learn more about DFIR-Orc.

Again, thank you for experimenting with our tool.

**Comment by Zakaren** [comment]
Hi, 

Thank you for your reply, I think the problem is solved. 

I have now the *DFIR-Orc.exe* on the *output* folder, after executing the *configure.cmd* file from an elevated prompt.
