### ISSUE TITLE
Offline mode not really offline for 2 modules

### ISSUE THREAD

**Issue by Croko-fr** [DFIR-ORC/dfir-orc-config#11]
Step to reproduce :

1. Launch DFIR-Orc in offline mode on the drive where you mounted your disk image or an empty existing partition

```bash
DFIR-Orc.exe /offline=F:\
```

2. Resulting archive : `DFIR-ORC_{SystemType}_{FullComputerName}_Offline.7z`

3. Look at BootCode.log and UefiFull.log

```bash
# Content :
Disk Name : \\.\PhysicalDrive0
```

-----------------------

Explaination :

There is no configuration file to define `%OfflineLocation%` as scope like all other modules.
I don't even know if both modules `GetLegacyBootCode_offline` and `GetUefiFull_offline` take a partition as parameter.

Perhaps working on full disk only ?

-----------------------

ISSUE :

You will get informations from your analysis machine in the Offline results.

**Comment by sc-anssi** [comment]
Sorry for the late fix...
