### ISSUE TITLE
Which version of dumpIT & winpmem ?

### ISSUE THREAD

**Issue by lightoyou** [DFIR-ORC/dfir-orc-config#13]
I try to configure ORC  but dumptIT not working which version or you using to have /q /n /u ?
Same question to winpmem.exe
Can you update the readme ?

**Comment by lightoyou** [comment]
With DumpIT in version 3.20190124.1

Change the config with :

``


        <command keyword="GetRam_dmp" optional="no" >
            <execute name="dumpit" run="7z:#Tools|dumpit" />
            <argument>/Q /N </argument>
            <output name="Dump_dumpit_{SystemType}_{FullComputerName}.dmp" source="File" argument="/O {FileName}" />
            <output name="Dump_dumpit_{SystemType}_{FullComputerName}.log" source="StdOutErr" />
        </command>



``

The version of winpmem.exe was probably 3.2 but for now the tools not work anymore with new windows distribution.
The new version 4.0RC2 from here https://github.com/Velocidex/WinPmem is still under development and have not all features backport so..

**Comment by sc-anssi** [comment]
Hi,
Sorry for the late reply. I believe the configuration was tested with DumpIt v3.0.20200902.2 and winpmem v3.3-rc2.
Regards.
