### ISSUE TITLE
I don't find DumpIt.exe  and winpmem.exe

### ISSUE THREAD

**Issue by anasjhze** [DFIR-ORC/dfir-orc-config#15]
Hello, 

I am installing the framework and I am at the configuration step. To complete the configuration, I can't find two tools: DumpIt.exe and winpmem.exe. 

I have searched on this platform: "https://live.sysinternals.com" but I did not find anything. 

I wonder where I can find these tools? 

Thanks for your help

**Comment by jeanga** [comment]
DumpIt was available from comae.com. I don't know if you can have it since then have been acquired by another company...

**Comment by jeanga** [comment]
For winpmem, velocidex has a download link for it here : https://winpmem.velocidex.com/

**Comment by anasjhze** [comment]
> DumpIt was available from comae.com. I don't know if you can have it since then have been acquired by another company...

Thanks for the answer, I'am struggling to find it, can I replace it with "procdump" in order to configurate dfir-orc ?

**Comment by jeanga** [comment]
Nope procdump is for processes, not physical memory. Sorry

**Comment by anasjhze** [comment]
Finally i found  the exe "Dumpit" in the platform "SOURCEFORGE"
